// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "hello@aasumitro.id"
        },
		"license": {
            "name": "MIT",
            "url": "https://github.com/aasumitro/ginca/blob/master/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
		"/examples": {
			"get": {
				 "produces": [
                    "application/json"
                ],
                "summary": "Retrieves all examples data",
			},
			"post": {
				 "produces": [
                    "application/json"
                ],
                "summary": "Store new example data",
			},
		},
		"/examples/{id}": {
			"get": {
				 "produces": [
                    "application/json"
                ],
                "summary": "Retrieves examples data by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Example ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
 							"code": 200,
                        	"status": "OK",
                            "$ref": "#/definitions/domain.Example"
                        }
                    }
                }
			},
			"put": {
				 "produces": [
                    "application/json"
                ],
                "summary": "Update selected example data by id",
			},
			"delete": {
				 "produces": [
                    "application/json"
                ],
                "summary": "Destroy example data by id",
			},
		}
	},
    "definitions": {
        "domain.Example": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
 				"created_at": {
                    "type": "string"
                },
				"updated_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
            }
        }
    },
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/v1",
	Schemes:     []string{},
	Title:       "Blueprint Swagger API",
	Description: "Swagger API for Example Service Blueprint",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
